fixing yaml identation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,52 +10,48 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.12'
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
 
-    - name: Install project dependencies
-      run: | 
-        python -m pip install --upgrade pip
-        pip install --no-cache-dir -r requirements.txt
+      - name: Install project dependencies
+        run: | 
+          python -m pip install --upgrade pip
+          pip install --no-cache-dir -r requirements.txt
 
-    - name: Run tests
-      run: |
-        pytest -v
-      continue-on-error: true
+      - name: Run tests
+        run: |
+          pytest -v
+        continue-on-error: true  # This allows the job to continue even if tests fail
 
   build:
     runs-on: ubuntu-latest
     needs: test
 
     steps: 
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set-up Python
-      uses: actions/setup-python@v4
-      with: 
-        python-version: '3.12'
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with: 
+          python-version: '3.12'
 
-    - name: Build Docker image
-      run: | 
-        docker build -t laptop-scrapper .
+      - name: Build Docker image
+        run: | 
+          docker build -t laptop-scrapper .
 
-    - name: Run the container
-      run: |
-        docker run -d -p 8009:8009 laptop-scrapper
+      - name: Run the container
+        run: |
+          docker run -d -p 8009:8009 laptop-scrapper
 
-    - name: Wait for app to start
-      run: sleep 10  
+      - name: Wait for app to start
+        run: sleep 10  
 
-    - name: Check app health
-      run: curl -f http://localhost:8009 || exit 1
-    continue-on-error: true
-
-    - name: Show logs
-      run: docker logs $(docker ps -q --filter "ancestor=laptop-scrapper")
-
+      - name: Check app health
+        run: curl -f http://localhost:8009 || exit 1
+        continue-on-error: true  # This allo
